name: Request a site
description: Suggest a website that should get its 2019 design.
title: "[Request] "
labels: ["site request"]
body:
  - type: input
    id: url
    attributes:
      label: Website URL
      placeholder: https://example.com
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description (optional)
